export enum Status {
  INFINITE = "INFINITE",
  NO_SOLUTION = "NO_SOLUTION",
  FACTORISABLE = "FACTORISABLE",
  UNIQUE = "UNIQUE",
  NOT_FACTORISABLE = "NOT_FACTORISABLE",
  NOT_POSITIVE_DEF = "NOT_POSITIVE_DEF",
  ERROR = "ERROR",
  CONVERGED = "CONVERGED",
  DIVERGED = "DIVERGED",
  MAX = "MAX"
}
